version: "3.8"

services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # UI Neo4j Browser
      - "7687:7687"   # Bolt (connexion avec FastAPI)
    environment:
      - NEO4J_AUTH=neo4j/davdu815
    volumes:
      - ./neo4j/data:/data

  fastapi:
    build: ./fastapi
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HA_TOKEN=${HA_TOKEN}
      - HA_URL=${HA_URL}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=davdu815
